Algoritmo "covid"

Var
paises:vetor[1..15] de caractere
casos:vetor[1..15] de real
mortes:vetor[1..15] de real
casosord:vetor[1..15] de real
med: real
esc:inteiro
Inicio
para esc de 1 ate 15 passo 1 faca
     escreval("fale o nome do pais: ")
     leia(paises[esc])
     escreval("fale o numero de casos: ")
     leia(casos[esc])
     escreval("fale o numero de mortes: ")
     leia(mortes[esc])

fimpara

para esc de 1 ate 15 passo 1 faca
     med <- med + casos[esc]
fimpara
      escreval("A média é: ", med)
      escreval("A mediana é: ", casos[8])
Fimalgoritmo






















































 Suecia - 5.770
 Alemanha - 9.266
 França - 737.285
 Espanha - 28.576
 Italia - 35.215
 Reino Unido - 46.526
 Brasil - 102.034
 EUA - 163.215
 Belgica - 9.879
 Argentina - 4.764
 Colombia - 13.154
 Bolivia - 3.712
 Equador - 5.951
 Chile - 10.178
 Peru - 21.276
 
 //Casos
 EUA - 5.107.631
 Espanha - 322.980
 Reino Unido - 311.641
 Italia - 251.237
 Brasil - 3.068.138
 Franca - 20.124.437
 Alemanha - 218.742
 Belgica - 74.620
 Equador - 95.563
 Bolivia - 91.635
 Argentina - 253.855
 Peru - 483.133
 Suecia - 83.126
 Colombia - 397.623
 Chile - 376.616
 
 
 
 
 
 
 
 
 
 
 

Fimalgoritmo